<div class="card topic-card mt-lg-0 mt-3">
    <div class="card-body">
        <h4 class="card-title">Looking for something else?</h4>
        <h5>Search using keywords</h5>
        <form method="get" action="/learninghub/filter/" class="row g-2 mb-3" role="search">
            <label for="sSide" class="visually-hidden">Search</label>
            <div class="col-auto flex-grow-1">
                <input type="search" id="sSide" class="form-control" name="keyword" placeholder="Search catalogue" required>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary btn-sm" aria-label="Submit Search">
                    Search
                </button>
            </div>
        </form>
        <h5>Search using filters</h5>


        <p class="lh-sm fs-6 card-text"><small>Select a heading to show/hide the filters from that category. Select the <strong>Apply</strong> button when you want to apply the filters.</small></p> <?php
                                                                                                                                                                                                        if (!empty($_GET['group']) || !empty($_GET['topic']) || !empty($_GET['audience']) || !empty($_GET['delivery_method'])) :
                                                                                                                                                                                                            // Grab the current URL
                                                                                                                                                                                                            $url = $_SERVER['REQUEST_URI'];
                                                                                                                                                                                                            $currenturl = urldecode($url);
                                                                                                                                                                                                        ?> <div class="mb-3">
                <div class="row"> <?php if (!empty($gterms)) : ?> <div class="col-md-auto mb-2">
                            <div>Group</div> <?php foreach ($gterms as $g) : ?> <?php
                                                                                                                                                                                                                    $grpurl = $currenturl;
                                                                                                                                                                                                                    $replace = 'group[]=' . $g->slug . '';
                                                                                                                                                                                                                    $gurl = str_replace($replace, '', $grpurl);
                                                                                                                                                                                                                    $gurl = str_replace('&&', '&', $gurl);
                                                                                ?> <button aria-label="remove filter: <?= $g->name ?>" class="badge bg-dark-subtle border-0 fw-normal">
                                    <a href="<?= $gurl ?>" class="text-secondary-emphasis text-decoration-none"> <?= $g->name ?> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg ms-1" viewBox="0 0 16 16">
                                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
                                        </svg></a>
                                </button> <?php endforeach ?>
                        </div> <?php endif ?> <?php if (!empty($tterms)) : ?> <div class="col-md-auto mb-2">
                            <div>Topic</div> <?php foreach ($tterms as $t) : ?> <?php
                                                                                                                                                                                                                    $topurl = $currenturl;
                                                                                                                                                                                                                    $replace = 'topic[]=' . $t->slug . '';
                                                                                                                                                                                                                    $turl = str_replace($replace, '', $topurl);
                                                                                                                                                                                                                    $turl = str_replace('&&', '&', $turl);
                                                                                ?> <button aria-label="remove filter: <?= $t->name ?>" class="badge bg-dark-subtle border-0 fw-normal">
                                    <a href="<?= $turl ?>" class="text-secondary-emphasis text-decoration-none"> <?= $t->name ?> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg ms-1" viewBox="0 0 16 16">
                                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
                                        </svg></a>
                                </button> <?php endforeach ?>
                        </div> <?php endif ?> <?php if (!empty($aterms)) : ?> <div class="col-md-auto mb-2">
                            <div>Audience</div> <?php foreach ($aterms as $a) : ?> <?php
                                                                                                                                                                                                                    $audurl = $currenturl;
                                                                                                                                                                                                                    $replace = 'audience[]=' . $a->slug . '';
                                                                                                                                                                                                                    $aurl = str_replace($replace, '', $audurl);
                                                                                                                                                                                                                    $aurl = str_replace('&&', '&', $aurl);
                                                                                    ?> <button aria-label="remove filter: <?= $a->name ?>" class="badge bg-dark-subtle border-0 fw-normal">
                                    <a href="<?= $aurl ?>" class="text-secondary-emphasis text-decoration-none"> <?= $a->name ?> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg ms-1" viewBox="0 0 16 16">
                                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
                                        </svg></a>
                                </button> <?php endforeach ?>
                        </div> <?php endif ?> <?php if (!empty($dterms)) : ?> <div class="col-md-auto">
                            <div>Delivery Method</div> <?php foreach ($dterms as $d) : ?> <?php
                                                                                                                                                                                                                    $dmurl = $currenturl;
                                                                                                                                                                                                                    $replace = 'delivery_method[]=' . $d->slug . '';
                                                                                                                                                                                                                    $durl = str_replace($replace, '', $dmurl);
                                                                                                                                                                                                                    $durl = str_replace('&&', '&', $durl);
                                                                                            ?> <button aria-label="remove filter: <?= $d->name ?>" class="badge bg-dark-subtle border-0 fw-normal">
                                    <a href="<?= $durl ?>" class="text-secondary-emphasis text-decoration-none"> <?= $d->name ?> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg ms-1" viewBox="0 0 16 16">
                                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
                                        </svg></a>
                                </button> <?php endforeach ?>
                        </div> <?php endif ?> </div>
                
            </div> <?php endif ?> 
            <div class="accordion" id="filterCategories">
            
            <div class="accordion-item">
                <h4 class="accordion-header" id="topicsHeading">
                    <button class="accordion-button py-2 px-3 py-lg-3 collapsed " type="button" data-bs-toggle="collapse" data-bs-target="#collapseTopics" aria-expanded="false" aria-controls="collapseTopics">
                        <div class="d-flex flex-column align-items-start">
                            <span class="fw-semibold">Topic</span>
                            <span class="fs-6"><small>What is the learning about?</small></span>
                        </div>
                    </button>
                </h4>
                <div id="collapseTopics" class="accordion-collapse collapse" aria-labelledby="topicsHeading">
                    <div class="accordion-body bg-light-subtle">
                        <form action="/learninghub/filter" method="GET"> <?php if (!empty($_GET['group'])) : ?> <?php foreach ($_GET['group'] as $gid) : ?> <input type="hidden" name="group[]" value="<?= sanitize_text_field($gid) ?>"> <?php endforeach ?> <?php endif ?> <?php if (!empty($_GET['audience'])) : ?> <?php foreach ($_GET['audience'] as $aid) : ?> <input type="hidden" name="audience[]" value="<?= $aid ?>"> <?php endforeach ?> <?php endif ?> <?php if (!empty($_GET['delivery_method'])) : ?> <?php foreach ($_GET['delivery_method'] as $did) : ?> <input type="hidden" name="delivery_method[]" value="<?= $did ?>"> <?php endforeach ?> <?php endif ?> <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $topics = get_categories(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        array(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'taxonomy' => 'topics',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'orderby' => 'name',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'order' => 'ASC',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'hide_empty' => '0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?> <?php foreach ($topics as $t) : ?> <?php $active = '' ?> <?php if (!empty($_GET['topic']) && in_array($t->slug, $_GET['topic'])) $active = 'checked' ?> <div class="form-check fs-6">
                                    <input class="form-check-input" type="checkbox" value="<?= $t->slug ?>" name="topic[]" id="topic<?= $t->term_id ?>" <?= $active ?>>
                                    <label for="topic<?= $t->term_id ?>" class="<?php if ($active == 'checked') echo 'fw-semibold' ?>"> <?= $t->name ?> (<?= $t->count ?>) </label>
                                </div> <?php endforeach ?> <button class="btn btn-sm bg-gov-green mt-2 applybutton">Apply</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h4 class="accordion-header" id="audienceHeading">
                    <button class="accordion-button py-2 px-3 py-lg-3 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAudience" aria-expanded="false" aria-controls="collapseAudience">
                        <div class="d-flex flex-column align-items-start">
                            <span class="fw-semibold">Audience</span>
                            <span class="fs-6"><small>Who is the learning for?</small></span>
                        </div>
                    </button>
                </h4>
                <div id="collapseAudience" class="accordion-collapse collapse" aria-labelledby="audienceHeading">
                    <div class="accordion-body bg-light-subtle">
                        <form action="/learninghub/filter" method="GET"> <?php if (!empty($_GET['group'])) : ?> <?php foreach ($_GET['group'] as $gid) : ?> <input type="hidden" name="group[]" value="<?= $gid ?>"> <?php endforeach ?> <?php endif ?> <?php if (!empty($_GET['topic'])) : ?> <?php foreach ($_GET['topic'] as $tid) : ?> <input type="hidden" name="topic[]" value="<?= $tid ?>"> <?php endforeach ?> <?php endif ?> <?php if (!empty($_GET['delivery_method'])) : ?> <?php foreach ($_GET['delivery_method'] as $did) : ?> <input type="hidden" name="delivery_method[]" value="<?= $did ?>"> <?php endforeach ?> <?php endif ?> <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $audiences = get_categories(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        array(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'taxonomy' => 'audience',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'orderby' => 'id',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'order' => 'DESC',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'hide_empty' => '0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?> <?php foreach ($audiences as $a) : ?> <?php $active = '' ?> <?php if (!empty($_GET['audience']) && in_array($a->slug, $_GET['audience'])) $active = 'checked' ?> <div class="form-check fs-6">
                                    <input class="form-check-input" type="checkbox" value="<?= $a->slug ?>" name="audience[]" id="audience<?= $a->term_id ?>" <?= $active ?>>
                                    <label for="audience<?= $a->term_id ?>" class="<?php if ($active == 'checked') echo 'fw-semibold' ?>"> <?= $a->name ?> (<?= $a->count ?>) </label>
                                </div> <?php endforeach ?> <button class="btn btn-sm bg-gov-green mt-2 applybutton">Apply</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h4 class="accordion-header" id="deliveryHeading">
                    <button class="accordion-button py-2 px-3 py-lg-3 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseDelivery" aria-expanded="false" aria-controls="collapseDelivery">
                        <div class="d-flex flex-column align-items-start">
                            <span class="fw-semibold">Delivery Method </span>
                            <span class="fs-6"><small>How is the learning offered?</small></span>
                        </div>
                    </button>
                </h4>
                <div id="collapseDelivery" class="accordion-collapse collapse" aria-labelledby="deliveryHeading">
                    <div class="accordion-body bg-light-subtle">
                        <form action="/learninghub/filter" method="GET"> <?php if (!empty($_GET['group'])) : ?> <?php foreach ($_GET['group'] as $gid) : ?> <input type="hidden" name="group[]" value="<?= $gid ?>"> <?php endforeach ?> <?php endif ?> <?php if (!empty($_GET['topic'])) : ?> <?php foreach ($_GET['topic'] as $tid) : ?> <input type="hidden" name="topic[]" value="<?= $tid ?>"> <?php endforeach ?> <?php endif ?> <?php if (!empty($_GET['audience'])) : ?> <?php foreach ($_GET['audience'] as $auid) : ?> <input type="hidden" name="audience[]" value="<?= $auid ?>"> <?php endforeach ?> <?php endif ?> <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $dms = get_categories(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        array(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'taxonomy' => 'delivery_method',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'orderby' => 'id',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'order' => 'DESC',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'hide_empty' => '0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ); //,'include' => array(3,37,82,236,410)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?> <?php foreach ($dms as $d) : ?> <?php $active = '' ?> <?php if (!empty($_GET['delivery_method']) && in_array($d->slug, $_GET['delivery_method'])) $active = 'checked' ?> <div class="form-check fs-6">
                                    <input class="form-check-input" type="checkbox" value="<?= $d->slug ?>" name="delivery_method[]" id="delivery_method<?= $d->term_id ?>" <?= $active ?>>
                                    <label for="delivery_method<?= $d->term_id ?>" class="<?php if ($active == 'checked') echo 'fw-semibold' ?>"> <?= $d->name ?> (<?= $d->count ?>) </label>
                                </div> <?php endforeach ?> <button class="btn btn-sm bg-gov-green mt-2 applybutton">Apply</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>